language: go
go:
- 1.14.x
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: DYmANisNNkgCtb8X7DxeUwLRSpuUtqFUUIBiIrF4RqITnnTTvgjGU7xgCeFmY+B7Xm7RAFnRBcUSvGPIfp1ONWpnksr5ZUDy9/naGKKLkLoNmhZoPZMpsaiLBx2Nn3kOSm8u5JypuuGpd7s3h3DWP7wQvMWc1CIR9zHhP/od68tHjagOiUnVwJGafSj8NRgPpA+hvBcGt26LYffAw8p0IlXcNXZwH4mMdGLn1SjA7wImmnoC+esMjAdbBbPE+EU44cAcivzj6f++WJSKQY1NXtQpIwBrHgUEd3GX4SMXJdZTWBSbjQL4RLy3k/+0GTXq3SyYTxOhptcg+NBjO7q7pqq0kogVrPHISYvsm3V/hxb4EnHP93OYNsQW+Pi2ARA1mYPJl/Zn+H19tJHVKtzJ/3ar1nW05qtl3aOkBifqSk69rN8fy5Ab1SepU5bzrUroNMc59DB6SDvFJtsRki6MISabXX3sjsV5fyf2NUeIUNDLCQPovPcDonfFR2FQ43ytt6BUrT5mlx0eQg2lQ7F/L/JP2wWrqpbjC0MxPRtCSvYEe3Wc9ANmhdLjdROmkNhK8yS9US+AWCAqet77sUDpPzs+J/7jI4IZ9wwWYeC/+GneaYvJQSZRITiTs3H7hilY3nKuVMHjn4ZnH6GHxBabAL2j9odmB1RPxl484dc6P1M=
  skip_cleanup: true
  app:
    master: website-neilb
